data= [
    {"name": "Virat Kohli", "followers": 270, "description": "Cricketer"},
    {"name": "Shraddha Kapoor", "followers": 94, "description": "Actress"},
    {"name": "Narendra Modi", "followers": 95, "description": "Politician"},
    {"name": "Priyanka Chopra", "followers": 92, "description": "Actress"},
    {"name": "Alia Bhatt", "followers": 86, "description": "Actress"},
    {"name": "Katrina Kaif", "followers": 80, "description": "Actress"},
    {"name": "Deepika Padukone", "followers": 80, "description": "Actress"},
    {"name": "Neha Kakkar", "followers": 78, "description": "Singer"},
    {"name": "Urvashi Rautela", "followers": 73, "description": "Actress"},
    {"name": "Salman Khan", "followers": 70, "description": "Actor"},
    {"name": "Jacqueline Fernandez", "followers": 71, "description": "Actress"},
    {"name": "Akshay Kumar", "followers": 66, "description": "Actor"},
    {"name": "Anushka Sharma", "followers": 65, "description": "Actress"},
    {"name": "Disha Patani", "followers": 57, "description": "Actress"},
    {"name": "Kriti Sanon", "followers": 54, "description": "Actress"},
    {"name": "Allu Arjun", "followers": 50, "description": "Actor"},
    {"name": "Hrithik Roshan", "followers": 48, "description": "Actor"},
    {"name": "Shah Rukh Khan", "followers": 47, "description": "Actor"},
    {"name": "Ranveer Singh", "followers": 46, "description": "Actor"},
    {"name": "MS Dhoni", "followers": 45, "description": "Cricketer"},
    {"name": "Sachin Tendulkar", "followers": 45, "description": "Cricketer"},
    {"name": "Rashmika Mandanna", "followers": 40, "description": "Actress"},
    {"name": "Rohit Sharma", "followers": 35, "description": "Cricketer"},
    {"name": "Samantha Ruth Prabhu", "followers": 35, "description": "Actress"},
    {"name": "Kajal Aggarwal", "followers": 30, "description": "Actress"},
    {"name": "Tamannaah Bhatia", "followers": 25, "description": "Actress"},
    {"name": "Pooja Hegde", "followers": 25, "description": "Actress"},
    {"name": "Vijay Deverakonda", "followers": 20, "description": "Actor"},
    {"name": "Arijit Singh", "followers": 20, "description": "Singer"},
    {"name": "Mahesh Babu", "followers": 15, "description": "Actor"},
    {"name": "Badshah", "followers": 15, "description": "Rapper"},
    {"name": "Diljit Dosanjh", "followers": 15, "description": "Singer"},
    {"name": "Ram Charan", "followers": 16, "description": "Actor"},
    {"name": "Yo Yo Honey Singh", "followers": 10, "description": "Rapper"},
    {"name": "Jr NTR", "followers": 10, "description": "Actor"},
    {"name": "Keerthy Suresh", "followers": 8, "description": "Actress"},
    {"name": "Yash", "followers": 8, "description": "Actor"},
    {"name": "Anushka Shetty", "followers": 7, "description": "Actress"},
    {"name": "Nani", "followers": 7, "description": "Actor"},
    {"name": "Sai Pallavi", "followers": 6, "description": "Actress"},
    {"name": "Chiranjeevi", "followers": 5, "description": "Actor"},
    {"name": "Nagarjuna Akkineni", "followers": 4, "description": "Actor"},
    {"name": "Akkineni Naga Chaitanya", "followers": 4, "description": "Actor"},
    {"name": "Ram Pothineni", "followers": 4, "description": "Actor"},
    {"name": "Pawan Kalyan", "followers": 4, "description": "Actor"},
    {"name": "Akhil Akkineni", "followers": 3, "description": "Actor"},
    {"name": "Varun Tej", "followers": 3, "description": "Actor"},
    {"name": "Ravi Teja", "followers": 3, "description": "Actor"},
    {"name": "Nithiin", "followers": 2, "description": "Actor"},
    {"name": "Sai Dharam Tej", "followers": 2, "description": "Actor"}
]
